spring.application.name=plus-project
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bookstore-db?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=dkzkfld12#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.datasource.hikari.pool-name=MyHikariPool
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.servlet.session.timeout=30m
jwt.secret.key=kfjasdifjaosijdfpaosidfjasidfjapwoeifjasddd12d122d12d12d1h98h892d1h8912d8h912dd21dqwdq12
