spring.application.name=plus-project
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# Spring Boot?? ????? ???? ??? ?
spring.datasource.hikari.pool-name=MyHikariPool

# Hibernate? ???? SQL ??? ??? ??
spring.jpa.properties.hibernate.show_sql=true
# ??? SQL? ????? ?? ?? ??
spring.jpa.properties.hibernate.format_sql=true
# SQL ??? **??(comment)**? ?? ?? ?? ??? ???? ??? ?? ??? ??? ??? ? ??
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret.key=YXNkZmphc2RmKjEyM2phc2RmIXNkZmFzZGZhc2RmYXNkZmpzZGZhc2RmYXNkZg==
aladin.api.key=ttbkimybeom1149001

spring.cache.type=redis
spring.cache.cache-names=userOrdersCache,boardSearchCache
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.client.registration.kakao.client-id=268a8b6e4e4c8d88e22ca485f31cfc78
spring.security.oauth2.client.registration.kakao.client-secret=z63orp5R4rkBH49bOyitI2gZcan9ZmkY
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=https://localhost:8080/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
