name: Java CI for feat/book Branch

on:
  push:
    branches: [ "feat/book" ]
  pull_request:
    branches: [ "feat/book" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: bookstore-db
          MYSQL_ROOT_PASSWORD: "dkzkfld12#"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: MySQL 준비될 때까지 대기
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            nc -z mysql 3306 && echo "MySQL is up!" && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드
        run: ./gradlew clean build --stacktrace
